export const ASSISTANT_SET_PANEL = 'ASSISTANT_SET_PANEL';
export const ASSISTANT_TOGGLE_PANEL = 'ASSISTANT_TOGGLE_PANEL';
export const ASSISTANT_SET_PROVIDER = 'ASSISTANT_SET_PROVIDER';
export const ASSISTANT_SET_MODEL = 'ASSISTANT_SET_MODEL';
export const ASSISTANT_ADD_ATTACHMENT = 'ASSISTANT_ADD_ATTACHMENT';
export const ASSISTANT_REMOVE_ATTACHMENT = 'ASSISTANT_REMOVE_ATTACHMENT';
export const ASSISTANT_CLEAR_ATTACHMENTS = 'ASSISTANT_CLEAR_ATTACHMENTS';
export const ASSISTANT_ADD_MESSAGE = 'ASSISTANT_ADD_MESSAGE';
export const ASSISTANT_STREAM_TEXT = 'ASSISTANT_STREAM_TEXT';
export const ASSISTANT_STREAM_RESET = 'ASSISTANT_STREAM_RESET';
export const ASSISTANT_TOOL_START = 'ASSISTANT_TOOL_START';
export const ASSISTANT_TOOL_RESULT = 'ASSISTANT_TOOL_RESULT';
export const ASSISTANT_TOOL_CLEAR = 'ASSISTANT_TOOL_CLEAR';
export const ASSISTANT_SET_RUN_STATE = 'ASSISTANT_SET_RUN_STATE';
export const ASSISTANT_SET_ERROR = 'ASSISTANT_SET_ERROR';
export const ASSISTANT_SECTION_PROGRESS = 'ASSISTANT_SECTION_PROGRESS';
export const ASSISTANT_SET_MAX_STEPS = 'ASSISTANT_SET_MAX_STEPS';
export const ASSISTANT_SET_STEP_LIMIT = 'ASSISTANT_SET_STEP_LIMIT';
export const ASSISTANT_SEND = 'ASSISTANT_SEND';
export const ASSISTANT_CLEAR = 'ASSISTANT_CLEAR';

export default {
    setPanel: ASSISTANT_SET_PANEL,
    togglePanel: ASSISTANT_TOGGLE_PANEL,
    setProvider: ASSISTANT_SET_PROVIDER,
    setModel: ASSISTANT_SET_MODEL,
    addAttachment: ASSISTANT_ADD_ATTACHMENT,
    removeAttachment: ASSISTANT_REMOVE_ATTACHMENT,
    clearAttachments: ASSISTANT_CLEAR_ATTACHMENTS,
    addMessage: ASSISTANT_ADD_MESSAGE,
    streamText: ASSISTANT_STREAM_TEXT,
    streamReset: ASSISTANT_STREAM_RESET,
    toolStart: ASSISTANT_TOOL_START,
    toolResult: ASSISTANT_TOOL_RESULT,
    toolClear: ASSISTANT_TOOL_CLEAR,
    setRunState: ASSISTANT_SET_RUN_STATE,
    setError: ASSISTANT_SET_ERROR,
    sectionProgress: ASSISTANT_SECTION_PROGRESS,
    setMaxSteps: ASSISTANT_SET_MAX_STEPS,
    setStepLimit: ASSISTANT_SET_STEP_LIMIT,
    send: ASSISTANT_SEND,
    clear: ASSISTANT_CLEAR
};
